from PIL import Image, ImageFilter

# img = Image.open('./Pokedex/pikachu.jpg')
# filtered_img = img.convert('L')
# box = (100, 100, 400, 400)
# region = filtered_img.crop(box)
# region.save("grey.png", 'png')
# filtered_img.save("grey.png", 'png')
# filtered_img.show()
# crooked = filtered_img.rotate(90)
# crooked.save("grey.png", 'png')
# resize = filtered_img.resize((300, 300))
# resize.save("grey.png", 'png')
img = Image.open('./astro.jpg')
# new_img = img.resize((400, 200))
img.thumbnail((400, 400))
img.save('thumbnail.jpg')
